baseURL = "http://emmgro.github.io/"
languageCode = "en-us"
author = "Emmanuelle Guerrero"
title = "Emmanuelle Guerrero - Web Developer, Photographer"
layoutdir           = "layouts"
publishdir          = "public"
theme = "cocoa"
#disqusshortname = "emmgr"

#[[menu.main]]
#name                   = "Blog"
#weight                 = -120
#identifier             = "blog"
#url                    = "/blog/"

# [[menu.main]]
# name                   = "Resume"
# weight                 = -120
# identifier             = "resume"
# hrefTargetBlank        = true
# url                    = "https://www.dropbox.com/s/c82xnw731a1s2iw/resume.pdf?dl=0"


[[menu.main]]
name                   = "About"
weight                 = -120
identifier             = "about"
url                    = "/about/"

[[menu.main]]
name                   = "Portfolio"
weight                 = -120
identifier             = "portfolio"
url                    = "/portfolio/"

[[menu.main]]
name                   = "Photography"
weight                 = -120
identifier             = "photography"
url                    = "/photo/"

[params]
author = "Emmanuelle Guerrero"
gravatar = "bc19a431cf19d6c3a6b609b3f22ce05a?s=80"
description = "Resume / Portfolio website for Emmanuelle Alejandro Guerrero Santana"
email = "emmaguerreros@gmail.com"
github = "//github.com/emmgro"
msn = "//m.me/emmgro"
instagram = "//instagram.com/emmgros/"
extracssfiles          = [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.
faviconfile = "img/profile.png"
selfintro = "Front-End UI Developer"

